// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOqagF-fGQ9GksOmRaAzpaU8ZYzgQj9Nc',
    appId: '1:914391963155:web:96a5c04a832fe8331611e6',
    messagingSenderId: '914391963155',
    projectId: 't-ride-ee6ee',
    authDomain: 't-ride-ee6ee.firebaseapp.com',
    storageBucket: 't-ride-ee6ee.firebasestorage.app',
    measurementId: 'G-X9CLHM3LDT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPtnMzsbX9CAnWMk6pL44w1kXHm1cIDJU',
    appId: '1:914391963155:android:4be271b1097822311611e6',
    messagingSenderId: '914391963155',
    projectId: 't-ride-ee6ee',
    storageBucket: 't-ride-ee6ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABPWJLYzwcFxLRLSD9BBfcgXIMAw7-4qY',
    appId: '1:914391963155:ios:86e853b4b6fd081e1611e6',
    messagingSenderId: '914391963155',
    projectId: 't-ride-ee6ee',
    storageBucket: 't-ride-ee6ee.firebasestorage.app',
    iosBundleId: 'com.example.tRideRiderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCi-Ud4GrLe9R2hZmqwId9_oYRXQSVJzSk',
    appId: '1:914391963155:web:b2566fac20818a011611e6',
    messagingSenderId: '914391963155',
    projectId: 't-ride-ee6ee',
    authDomain: 't-ride-ee6ee.firebaseapp.com',
    storageBucket: 't-ride-ee6ee.firebasestorage.app',
    measurementId: 'G-LYYBW5CENB',
  );
}
